# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: auditproxy

before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod tidy
builds:
  -
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w

archives:
  - format: binary

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
